version: '3.8'

services:
  # Servidor Local Edge (Sincronizador e Banco)
  db:
    image: postgres:15-alpine
    container_name: fabrichair_edge_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fabrichair
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - edge_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # ERP Local (Bolha de Armazenagem)
  erp:
    build: .
    container_name: fabrichair_edge_erp
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve a configuração local apontando para o container "db"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fabrichair
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TZ: America/Sao_Paulo
    depends_on:
      - db
    restart: unless-stopped

volumes:
  # Garante que os dados nao sumam se reiniciar o PC
  edge_pgdata:
